---
downloads: ~/.ansible-downloads/

configure_dotfiles: true
configure_terminal: true
configure_osx: true

# Set to 'true' to configure the Dock via dockutil.
configure_dock: false
dockitems_remove:
  - Launchpad
  - TV
  - Podcasts
  - 'App store'
  - Messages
  - Maps
  - Photos
  - FaceTime
  - Contacts
  - Reminders
  - Notes
  - Music
dockitems_persist: []
# - name: "Sublime Text"
#   path: "/Applications/Sublime Text.app/"
#   pos: 5

configure_sudoers: false
sudoers_custom_config: ''
# Example:
# sudoers_custom_config: |
#   # Allow users in admin group to use sudo with no password.
#   %admin ALL=(ALL) NOPASSWD: ALL

dotfiles_repo: https://www.github.com/arnoutvw/dotfiles.git
dotfiles_repo_accept_hostkey: true
dotfiles_repo_local_destination: ~/Development/GitHub/dotfiles
dotfiles_files:
  - .zshrc
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  - git
  - bash-completion
  - httpie
  - nvm
  - node
  - ssh-copy-id
  - zsh-history-substring-search
  - k9s
  - maven
  - wget
  - gradle
  - zsh

homebrew_taps:
  - homebrew/core
  - homebrew/cask

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  - firefox
  - google-chrome
  - sublime-text
  - transmit
#  - intellij-idea
  - microsoft-teams
  - textmate
  - parsec
  - alfred
  - beyond-compare
  - choosy
  - cleanmymac
  - coconutbattery
  - ipvanish-vpn
  - iterm2
  - microsoft-office
  - postman
  - royal-tsx
  - sequel-pro
  - scroll-reverser
  - spotify
  - spotify-now-playing
  - visualvm
  - syncthing
  - vagrant
  - vagrant-manager
  - 1password-cli

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1333542190, name: "1Password" }
  - { id: 904280696, name: "Things" }
  - { id: 417375580, name: "BetterSnapTool" }
  - { id: 823766827, name: "OneDrive" }
  - { id: 1455214828, name: "MQTT Explorer" }
  - { id: 425424353, name: "The Unarchiver" }
  - { id: 1099568401, name: "Home assistant" }
  - { id: 937984704, name: "Amphetamine" }
  - { id: 407963104, name: "Pixelmator" }
  - { id: 411643860, name: "DaisyDisk" }
  - { id: 1147396723, name: "WhatsApp" }
  - { id: 1510445899, name: "Meeter" }
  - { id: 803453959, name: "Slack" }
  - { id: 290986013, name: "Deliveries" }
  - { id: 1451685025, name: "WireGuard" }
mas_email: ""
mas_password: ""

osx_script: "~/.osx --no-restart"

# Install packages from other package managers.
# Note: You are responsible for making sure the required package managers are
# installed, eg. through homebrew.
composer_packages: []
# - name: drush
#   state: present # present/absent, default: present
#   version: "^8.1" # default: N/A
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

# Set to 'true' to configure Sublime Text.
configure_sublime: true
sublime_base_path: '~/Library/Application Support/Sublime Text'
sublime_config_path: "Packages/User"
sublime_package_control:
  - "DocBlockr"
  - "Dockerfile Syntax Highlighting"
  - "FileDiffs"
  - "GitHub Flavored Markdown Preview"
  - "Jinja2"
  - "Package Control"
  - "PHP-Twig"
  - "Pretty JSON"
  - "SublimeLinter"
  - "SublimeLinter-contrib-yamllint"
  - "TrailingSpaces"
  - "WordCount"
  - "Indent XML"
  - "Indent JSON"

# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []

install_jdk: true
sdkman_update: true
sdkman_auto_answer: true
sdkman_install_packages:
  - { candidate: java, version: 8.0.302-tem }
  - { candidate: java, version: 11.0.12-tem }
  - { candidate: java, version: 17.0.1-tem }
sdkman_defaults:
  java: 11.0.12-tem

#zsh
ohmyzsh_theme: agnoster
ohmyzsh_plugins:
  - git
  - mvn
  - textmate
  - cp
  - docker
  - github
  - java
  - npm
  - brew
  - kubectl
  - history
  - history-substring-search

copy_ssh_config: true

intellij_edition: ultimate